### ISSUE TITLE
Pink blobs

### ISSUE THREAD

**Issue by davelandrygmail** [markuskruse/stl-librarian#1]
Hello - I'm a complete blender newbie (in fact I installed it just for this)

The generated jpgs are completely pink (not pink and blue like your screenshot)

I'm I missing something obvious?

Thanks
![Capture](https://user-images.githubusercontent.com/51218913/65926092-72756400-e3c1-11e9-85c7-2c420e284e3c.JPG)

**Comment by markuskruse** [comment]
I will take a look. But terribly busy at the moment, with kickstarter and work. :-(

**Comment by markuskruse** [comment]
Right, I can at least confirm this bug. Will work on it tonite.

**Comment by markuskruse** [comment]
This was a missing image texture. The application isn't using the image texture anymore.
